;; apsp-l
(sum (var w)
     (* (+ (rel E (var x) (var z) (var w))
           (sum (var y)
                (sum (var w1)
                     (sum (var w2)
                          (* (* (rel R (var x) (var y) (var w1))
                                (rel E (var y) (var z) (var w2)))
                             (I (= (var w) (* (var w1) (var w2)))))))))
        (var w)))

;; apsp-norm
(+ (sum (var w) (* (var w) (rel E (var x) (var z) (var w))))
   (sum (var y)
        (sum (var w1)
             (sum (var w2)
                  (* (* (rel R (var x) (var y) (var w1))
                        (rel E (var y) (var z) (var w2)))
                     (* w1 w2))))))

;; apsp-r
(+ (sum (var w)
        (* (var w)
           (rel E (var x) (var z) (var w))))
   (sum (var y)
        (* (sum (var w1)
                (* (var w1)
                   (rel R (var x) (var y) (var w1))))
           (sum (var w2)
                (* (var w2)
                   (rel E (var y) (var z) (var w2)))))))

;; apsp-1
(+ (sum (var w)
        (* (var w)
           (rel E (var x) (var z) (var w))))
   (sum (var w)
        (sum (var y)
                (sum (var w1)
                     (sum (var w2)
                          (* (* (var w)
                                (I (= (var w) (* (var w1) (var w2)))))
                             (* (rel R (var x) (var y) (var w1))
                                (rel E (var y) (var z) (var w2)))))))))

;; apsp-2
(+ (sum (var w)
        (* (var w)
           (rel E (var x) (var z) (var w))))
   (sum (var y)
        (sum (var w1)
             (sum (var w2)
                  (* (* (rel R (var x) (var y) (var w1))
                        (rel E (var y) (var z) (var w2)))
                     (sum (var w)
                          (* (var w)
                             (I (= (var w) (* (var w1) (var w2)))))))))))

;; apsp-3
(+ (sum (var w)
        (* (var w)
           (rel E (var x) (var z) (var w))))
   (sum (var y)
        (sum (var w1)
             (sum (var w2)
                  (* (* (rel R (var x) (var y) (var w1))
                        (rel E (var y) (var z) (var w2)))
                     (* (var w1) (var w2)))))))

;; apsp-4
(+ (sum (var w)
        (* (var w)
           (rel E (var x) (var z) (var w))))
   (sum (var y)
        (sum (var w1)
             (sum (var w2)
                  (* (* (rel R (var x) (var y) (var w1))
                        (var w1))
                     (* (rel E (var y) (var z) (var w2))
                        (var w2)))))))

;; running-total-l
(sum (var w)
     (sum (var j)
          (* (* (var w) (* (I (<= 1 (var j)))
                           (I (<= (var j) (var t)))))
             (+ (* (I (= (var t) (var j)))
                   (rel v (var j) (var w)))
                (* (rel R (- (var t) 1) (var j) (var w))
                   (* (I (< (var j) (var t)))
                      (I (> (var t) 1))))))))

;; runnin-total-r
(+ (* (I (> (var t) 1))
      (sum (var j)
           (sum (var w)
                (* (* (rel R (- (var t) 1) (var j) (var w))
                      (var w))
                   (* (I (<= (var j) (- (var t) 1)))
                      (I (<= 1 (var j))))))))
   (sum (var j)
        (sum (var w)
             (* (* (rel v (var j) (var w))
                   (var w))
                (* (I (= (var t) (var j)))
                   (I (<= 1 (var j))))))))

;; sliding-window-l
(- (sum (var w)
     (sum (var j)
          (* (* (var w) (* (I (<= 1 (var j)))
                           (I (<= (var j) (var t)))))
             (+ (* (I (= (var t) (var j)))
                   (rel v (var j) (var w)))
                (* (rel R (- (var t) 1) (var j) (var w))
                   (* (I (< (var j) (var t)))
                      (I (> (var t) 1))))))))
   (sum (var w)
     (sum (var j)
          (* (* (var w) (* (I (<= 1 (var j)))
                           (I (<= (var j) (- (var t) (var k))))))
             (+ (* (I (= (- (var t) (var k)) (var j)))
                   (rel v (var j) (var w)))
                (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                   (* (I (< (var j) (- (var t) (var k))))
                      (I (> (- (var t) (var k)) 1)))))))))

;; sliding-window-l
(- (sum (var w)
     (sum (var j)
          (* (* (var w) (* (I (<= 1 (var j)))
                           (I (<= (var j) (var t)))))
             (+ (* (I (= (var t) (var j)))
                   (rel v (var j) (var w)))
                (* (rel R (- (var t) 1) (var j) (var w))
                   (* (I (< (var j) (var t)))
                      (I (> (var t) 1))))))))
   (sum (var w)
     (sum (var j)
          (* (* (var w) (* (I (<= 1 (var j)))
                           (I (<= (var j) (- (var t) (var k))))))
             (+ (* (I (= (- (var t) (var k)) (var j)))
                   (rel v (var j) (var w)))
                (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                   (* (I (< (var j) (- (var t) (var k))))
                      (I (> (- (var t) (var k)) 1)))))))))

;; sliding-window-1
(- (+ (* (I (> (var t) 1))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (var t) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (var t) 1)))
                         (I (<= 1 (var j))))))))
      (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (var t) (var j)))
                      (I (<= 1 (var j))))))))
   (+ (* (I (> (- (var t) (var k)) 1))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                         (I (<= 1 (var j))))))))
      (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (- (var t) (var k)) (var j)))
                      (I (<= 1 (var j)))))))))

;; sliding-window-2
(+ (- (* (I (> (var t) 1))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (var t) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (var t) 1)))
                         (I (<= 1 (var j))))))))
      (* (I (> (- (var t) (var k)) 1))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                         (I (<= 1 (var j)))))))))
   (- (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (var t) (var j)))
                      (I (<= 1 (var j)))))))
      (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (- (var t) (var k)) (var j)))
                      (I (<= 1 (var j)))))))))

;; sliding-window-3
(+ (- (* (I (> (var t) 1))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (var t) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (var t) 1)))
                         (I (<= 1 (var j))))))))
      (* (* (I (> (- (var t) (var k)) 1)) (I (> (var t) 1)))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                         (I (<= 1 (var j)))))))))
   (- (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (var t) (var j)))
                      (I (<= 1 (var j)))))))
      (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (- (var t) (var k)) (var j)))
                      (I (<= 1 (var j)))))))))

;; sliding-window-4
(+ (- (* (I (> (var t) 1))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (var t) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (var t) 1)))
                         (I (<= 1 (var j))))))))
      (* (- (I (> (var t) 1))
            (* (I (> (var t) 1))
               (I (<= (- (var t) (var k)) 1))))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                         (I (<= 1 (var j)))))))))
   (- (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (var t) (var j)))
                      (I (<= 1 (var j)))))))
      (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (- (var t) (var k)) (var j)))
                      (I (<= 1 (var j)))))))))

;; sliding-window-5
(+ (- (* (I (> (var t) 1))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (var t) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (var t) 1)))
                         (I (<= 1 (var j))))))))
      (- (* (I (> (var t) 1))
            (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                         (I (<= 1 (var j))))))))
         (* (* (I (> (var t) 1))
               (I (<= (- (var t) (var k)) 1)))
            (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                         (I (<= 1 (var j))))))))))
   (- (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (var t) (var j)))
                      (I (<= 1 (var j)))))))
      (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (- (var t) (var k)) (var j)))
                      (I (<= 1 (var j)))))))))

;; sliding-window-6
(+ (+ (- (* (I (> (var t) 1))
            (sum (var j)
                 (sum (var w)
                      (* (* (rel R (- (var t) 1) (var j) (var w))
                            (var w))
                         (* (I (<= (var j) (- (var t) 1)))
                            (I (<= 1 (var j))))))))
         (* (I (> (var t) 1))
            (sum (var j)
                 (sum (var w)
                      (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                            (var w))
                         (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                            (I (<= 1 (var j)))))))))

      (* (* (I (> (var t) 1))
            (I (<= (- (var t) (var k)) 1)))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                         (I (<= 1 (var j)))))))))
   (- (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (var t) (var j)))
                      (I (<= 1 (var j)))))))
      (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (- (var t) (var k)) (var j)))
                      (I (<= 1 (var j)))))))))

;; sliding-window-7
(+ (+ (* (I (> (var t) 1))
         (- (sum (var j)
                 (sum (var w)
                      (* (* (rel R (- (var t) 1) (var j) (var w))
                            (var w))
                         (* (I (<= (var j) (- (var t) 1)))
                            (I (<= 1 (var j)))))))
            (sum (var j)
                 (sum (var w)
                      (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                            (var w))
                         (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                            (I (<= 1 (var j)))))))))
      (* (* (I (> (var t) 1))
            (I (<= (- (var t) (var k)) 1)))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                         (I (<= 1 (var j)))))))))
   (- (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (var t) (var j)))
                      (I (<= 1 (var j)))))))
      (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (- (var t) (var k)) (var j)))
                      (I (<= 1 (var j)))))))))

;; sliding-window-8
(+ (* (I (> (var t) 1))
      (- (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (var t) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (var t) 1)))
                         (I (<= 1 (var j)))))))
         (sum (var j)
              (sum (var w)
                   (* (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                         (var w))
                      (* (I (<= (var j) (- (- (var t) (var k)) 1)))
                         (I (<= 1 (var j)))))))))
   (- (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (var t) (var j)))
                      (I (<= 1 (var j)))))))
      (sum (var j)
           (sum (var w)
                (* (* (rel v (var j) (var w))
                      (var w))
                   (* (I (= (- (var t) (var k)) (var j)))
                      (I (<= 1 (var j)))))))))

;; sliding-window-l
(- (sum (var w)
     (sum (var j)
          (* (* (var w) (* (I (<= 1 (var j)))
                           (I (<= (var j) (var t)))))
             (+ (* (I (= (var t) (var j)))
                   (rel v (var j) (var w)))
                (* (rel R (- (var t) 1) (var j) (var w))
                   (* (I (< (var j) (var t)))
                      (I (> (var t) 1))))))))
   (sum (var w)
     (sum (var j)
          (* (* (var w) (* (I (<= 1 (var j)))
                           (I (<= (var j) (- (var t) (var k))))))
             (+ (* (I (= (- (var t) (var k)) (var j)))
                   (rel v (var j) (var w)))
                (* (rel R (- (- (var t) (var k)) 1) (var j) (var w))
                   (* (I (< (var j) (- (var t) (var k))))
                      (I (> (- (var t) (var k)) 1)))))))))
